disable C4996 Warning as in Win UWP warnings declared as errors
This was produced before:
- error C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.